# Pencere ayarları
GENISLIK = 400
YUKSEKLIK = 700
FPS = 60

# Platform ayarları
PLATFORM_YUKSEKLIK = 20
PLATFORM_GENISLIK_UZUN = 120
PLATFORM_GENISLIK_KISA = 60

# Oyuncu ayarları
OYUNCU_HIZ = 5
YERCEKIMI = 0.5
ZIPLAMA_GUCU = -10
YUKSEK_ZIP_GUCU = -18
SUPER_ZIP_GUCU = -24

# Item ayarları
HAVUC_GENISLIK = 60
HAVUC_YUKSEKLIK = 60
ITEM_GORUNME_SIKLIK = 6

# Platform kırılma ayarları
KIRILMA_SURESI = 2500
KIRILMA_HIZLANMA = 20
MIN_KIRILMA_SURESI = 800

# Renkler
GOK_MAVISI = (135, 206, 235)
BEYAZ = (255, 255, 255)
HAVUC_RENGI = (255, 165, 0)

# Arkaplan
ARKAPLAN_KATMAN = 3
ARKAPLAN_KAYMA_HIZI = 0.5

# Font ayarları (Yeni eklendi)
FONT_DOSYA = "./assets/PressStart2P-Regular.ttf"
FONT_BUYUK = 24
FONT_KUCUK = 16
